#This this an example of the most basic DockerFile
#before to build this image with this docker file we need to :
#open console , execute dotnet restore HeatMeterWebApi.csproj and  dotnet publish -o ./publish
 
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /app

COPY ./HeatMeterWebApi/publish .
ENTRYPOINT ["dotnet", "HeatMeterWebApi.dll"]